<script lang="ts">
  
  const techniques = [
      
  { name: "ETB1-Ldt", pdf: "/ETB1-Ldt.pdf" },
  { name: "ETB2-Prise d'eau", pdf: "/ETB2-Prise d'eau.pdf" },
  { name: "ETB3-Lance", pdf: "/ETB3-Lance.pdf" },
  { name: "ETB4-Alimentation", pdf: "/ETB4-Alimentation.pdf" },
  { name: "ETB5-Etablissement particuliers", pdf: "/ETB5-Etablissement particuliers.pdf" },
  { name: "ETB6-Prolongement/remplacement", pdf: "/ETB6-Prolongement/remplacement.pdf" },
  { name: "TDE1-Refroidissement des fumées", pdf: "/TDE1-Refroidissement des fumées.pdf" },
  { name: "TDE2-Extinction directe", pdf: "/TDE2-Extinction directe.pdf" },
  { name: "TDE3-Extinction indirecte", pdf: "/TDE3-Extinction indirecte.pdf" },
  { name: "TDE4-Extinction combinée/massive", pdf: "/TDE4-Extinction combinée/massive.pdf" },
  { name: "TDE5-Situation pre-backdraft", pdf: "/TDE5-Situation pre-backdraft.pdf" },
  { name: "TDE6-Repli sous protection hydraulique", pdf: "/TDE6-Repli sous protection hydraulique.pdf" },
  { name: "TDE7-Feu soumis aux effets du vent et effet chalumeau", pdf: "/TDE7-Feu soumis aux effets du vent et effet chalumeau.pdf" },
  { name: "TDE8-Attaque d'atténuation", pdf: "/TDE8-Attaque d'atténuation.pdf" },
  { name: "Contrôle croisé", pdf: "/Contrôle croisé.pdf" },
  { name: "Engagement a vue", pdf: "/Engagement a vue.pdf" },
  { name: "Engagement au moyen d'une ligne de vie", pdf: "/Engagement au moyen d'une ligne de vie.pdf" },
  { name: "Engagement sur ligne de vie méthode latérale", pdf: "/Engagement sur ligne de vie méthode latérale.pdf" },
  { name: "Engagement sur ligne de vie méthode circulaire", pdf: "/Engagement sur ligne de vie méthode circulaire.pdf" },
  { name: "Méthode AIDES", pdf: "/Méthode AIDES.pdf" },
  { name: "Deplacement-progression sous ARI", pdf: "/Deplacement-progression sous ARI.pdf" },
  { name: "Règle de marquage", pdf: "/Règle de marquage.pdf" },
  { name: "Utilisation échelle à coulisse en mode secours", pdf: "/Utilisation échelle à coulisse en mode secours.pdf" },
  { name: "Attendre les secours, binome en difficulté", pdf: "/Attendre les secours.pdf" },
  { name: "Passage dans des fils ou des câbles", pdf: "/Passage dans des fils ou des câbles.pdf" },
  { name: "Franchissement passage étroit", pdf: "/Franchissement passage étroit.pdf" },
  { name: "Retrait de l'ARI-Autosauvetage", pdf: "/Retrait de l'ARI-Autosauvetage.pdf" },
  { name: "Technique de respiration (gestion air)", pdf: "/Technique de respiration (gestion air).pdf" },
  { name: "Gérer une fuite", pdf: "/Gérer une fuite.pdf" },
  { name: "Bail-out", pdf: "/Bail-out.pdf" },
  { name: "Evacuation au moyen d'un tuyau", pdf: "/Evacuation au moyen d'un tuyau.pdf" },
  { name: "Evaluation et stabilisation d'un équipier en difficulté", pdf: "/Evaluation et stabilisation d'un équipier en difficulté.pdf" },
  { name: "Traction au sol d'un SP sans matériel", pdf: "/Traction au sol d'un SP sans matériel.pdf" },
  { name: "Traction au sol avec matériel", pdf: "/Traction au sol avec matériel.pdf" },
  { name: "Sauvetage par un binome", pdf: "/Sauvetage par un binome.pdf" },
  { name: "Evacuation par l'escalier", pdf: "/Evacuation par l'escalier.pdf" },
  { name: "Le Denver-drill", pdf: "/Le Denver-drill.pdf" },
  { name: "Technique d'évacuation de SP sur echelle à coulisse", pdf: "/Technique d'évacuation de SP sur echelle à coulisse.pdf" },
  { name: "Remontée d'un équipier avec sa lance", pdf: "/Remontée d'un équipier avec sa lance.pdf" },
  { name: "Le Nance-drill", pdf: "/Le Nance-drill.pdf" },
  { name: "Utilisation de l'échelle à crochet", pdf: "/Utilisation de l'échelle à crochet.pdf" },
  { name: "Cas particulier de l'utilisation de l'échelle à crochet", pdf: "/Cas particulier de l'utilisation de l'échelle à crochet.pdf" },
  { name: "Utilisation échelle à coulisse-sauvetage d'un victime valide", pdf: "/Utilisation échelle à coulisse-sauvetage d'un victime valide.pdf" },
  { name: "Utilisation échelle à coulisse-sauvetage d'un victime invalide", pdf: "/Utilisation échelle à coulisse-sauvetage d'un victime invalide.pdf" },
  { name: "Utilisation échelle à coulisse en excavation", pdf: "/Utilisation échelle à coulisse en excavation.pdf" },
  { name: "Accès à une personne visible en hauteur", pdf: "/Accès à une personne visible en hauteur.pdf" },
  { name: "Utilisation particulière de l'échelle à coulisse", pdf: "/Utilisation particulière de l'échelle à coulisse.pdf" },
  { name: "Dégagement d'urgence sans matériel", pdf: "/Dégagement d'urgence sans matériel.pdf" },
  { name: "Dégagement d'urgence avec matériel", pdf: "/Dégagement d'urgence avec matériel.pdf" },
  { name: "LSPCC-Sauvetage au moyen du harnais", pdf: "/LSPCC-Sauvetage au moyen du harnais.pdf" },
  { name: "LSPCC-Sauvetage par l'extérieur", pdf: "/LSPCC-Sauvetage par l'extérieur.pdf" },
  { name: "LSPCC-Excavation", pdf: "/LSPCC-Excavation.pdf" },
  { name: "LSPCC-Reconnaissance d'appartement", pdf: "/LSPCC-Reconnaissance d'appartement.pdf" },
  { name: "Décontamination aux fumées d'incendie", pdf: "/Décontamination aux fumées d'incendie.pdf" },
  { name: "Retournement en urgence d’une victime à 2", pdf: "/Retournement en urgence d’une victime à 2.pdf" },
  { name: "Retournement en urgence d’une victime à 1", pdf: "/Retournement en urgence d’une victime à 1.pdf" },
  { name: "Evaluer la respiration", pdf: "/Evaluer la respiration.pdf" },
  { name: "Evaluer la circulation", pdf: "/Evaluer la circulation.pdf" },
  { name: "Mesurer la glycémie capillaire", pdf: "/Mesurer la glycémie capillaire.pdf" },
  { name: "Mesurer la pression artérielle (auto-tensiomètre)", pdf: "/Mesurer la pression artérielle (auto-tensiomètre).pdf" },
  { name: "Mesure de la saturation en oxygène", pdf: "/Mesure de la saturation en oxygène.pdf" },
  { name: "Mesurer la température de la victime", pdf: "/Mesurer la température de la victime.pdf" },
  { name: "Evaluer la fonction neurologique", pdf: "/Evaluer la fonction neurologique.pdf" },
  { name: "Recherche de lésions", pdf: "/Recherche de lésions.pdf" },
  { name: "Équipement de protection risques infectieux", pdf: "/Équipement de protection risques infectieux.pdf" },
  { name: "Friction des mains", pdf: "/Friction des mains.pdf" },
  { name: "Lavage des mains", pdf: "/Lavage des mains.pdf" },
  { name: "Mise en place de gants stériles", pdf: "/Mise en place de gants stériles.pdf" },
  { name: "Nettoyage et désinfection d’un véhicule ou d’un local", pdf: "/Nettoyage et désinfection d’un véhicule ou d’un local.pdf" },
  { name: "Nettoyage et désinfection du matériel", pdf: "/Nettoyage et désinfection du matériel.pdf" },
  { name: "Retrait des gants à usage unique", pdf: "/Retrait des gants à usage unique.pdf" },
  { name: "Lavage occulaire", pdf: "/Lavage occulaire.pdf" },
  { name: "Aspiration de mucosités", pdf: "/Aspiration de mucosités.pdf" },
  { name: "Compression manuelle", pdf: "/Compression manuelle.pdf" },
  { name: "Compressions thoraciques (adultes)", pdf: "/Compressions thoraciques.pdf" },
  { name: "Compressions thoraciques (enfant)", pdf: "/Compressions thoraciques.pdf" },
  { name: "Compressions thoraciques (nourrisson, nouveau-né)", pdf: "/Compressions thoraciques.pdf" },
  { name: "Claques dans le dos (adulte et enfant)", pdf: "/Claques dans le dos.pdf" },
  { name: "Claques dans le dos (nourrisson)", pdf: "/Claques dans le dos.pdf" },
  { name: "Désostruction par compressions abdominales (adulte et enfant)", pdf: "/Désostruction par compressions abdominale.pdf" },
  { name: "Désostruction par compressions thoraciques (femme enceinte et obèse)", pdf: "/Désostruction par compressions.pdf" },
  { name: "Désostruction par compressions thoraciques (nourrisson)", pdf: "/Désostruction par compressions.pdf" },
  { name: "Pose d’un garrot", pdf: "/Pose d’un garrot.pdf" },
  { name: "LVA victime assise", pdf: "/LVA victime assise.pdf" },
  { name: "LVA victime non traumatisée", pdf: "/LVA victime non traumatisée.pdf" },
  { name: "LVA victime traumatisée", pdf: "/LVA victime traumatisée.pdf" },
  { name: "Mise en place d’une canule oropharyngée", pdf: "/Mise en place d’une canule oropharyngée.pdf" },
  { name: "Pose d’un pansement compressif (israélien)", pdf: "/Pose d’un pansement compressif (israélien).pdf" },
  { name: "Utilisation du DAE", pdf: "/Utilisation du DAE.pdf" },
  { name: "Ventilation artificielle orale (adulte, enfant)", pdf: "/Ventilation artificielle orale.pdf" },
  { name: "Ventilation artificielle orale (nourrisson, nouveau-né)", pdf: "/Ventilation artificielle orale.pdf" },
  { name: "Ventilation artificielle avec insufflateur (1 secouriste)", pdf: "/Ventilation artificielle avec insufflateur.pdf" },
  { name: "Ventilation artificielle avec insufflateur (2 secouristes)", pdf: "/Ventilation artificielle avec insufflateur.pdf" },
  { name: "PLS à 1 secouriste", pdf: "/PLS à 1 secouriste.pdf" },
  { name: "PLS à 2 secouristes", pdf: "/PLS à 2 secouristes.pdf" },
  { name: "Inhalation d’oxygène (masque haute concentration)", pdf: "/Administration d’oxygène par inhalation.pdf" },
  { name: "Utilisation d’une bouteille d’oxygène", pdf: "/Utilisation d’une bouteille d’oxygène.pdf" },
  { name: "Réchauffement d'une victime", pdf: "/Réchauffement d'une victime.pdf" },
  { name: "Position d’attente à plat dos", pdf: "/Position d’attente.pdf" },
  { name: "Position d’attente assise ou demi-assise", pdf: "/Position d’attente.pdf" },
  { name: "Position d’attente sur le côté", pdf: "/Position d’attente.pdf" },
  { name: "Position d’attente cuisses fléchies, jambes repliées", pdf: "/Position d’attente.pdf" },
  { name: "Aide à la prise de médicaments", pdf: "/Aide à la prise de médicaments.pdf" },
  { name: "Manoeuvres physiques", pdf: "/Manoeuvres physiques.pdf" },
  { name: "Soin au cordon", pdf: "/Soin au cordon.pdf" },
  { name: "Réaliser un pansement non-occlusif", pdf: "/Réaliser un pansement non-occlusif.pdf" },
  { name: "Contention pelvienne", pdf: "/Contention pelvienne.pdf" },
  { name: "Immobilisation d’un membre avec une attelle à dépression", pdf: "/Pose d’attelle à dépression.pdf" },
  { name: "Immobilisation de l'épaule avec une attelle à dépression", pdf: "/Pose d’attelle à dépression.pdf" },
  { name: "Écharpe simple", pdf: "/Écharpe.pdf" },
  { name: "Contre-écharpe", pdf: "/Écharpe.pdf" },
  { name: "Écharpe oblique", pdf: "/Écharpe.pdf" },
  { name: "Immobilisation victime plat dos sur plan dur", pdf: "/Immobilisation sur plan dur.pdf" },
  { name: "Immobilisation victime allongée sur le ventre sur plan dur", pdf: "/Immobilisation sur plan dur.pdf" },
  { name: "Immobilisation victime debout sur plan dur", pdf: "/Immobilisation sur plan dur.pdf" },
  { name: "Immobilisation au moyen du MID", pdf: "/Immobilisation au moyen du MID.pdf" },
  { name: "Maintien de la tête à 2 mains victime debout ou assise", pdf: "/Maintien de la tête.pdf" },
  { name: "Maintien de la tête à 2 mains victime plat dos", pdf: "/Maintien de la tête.pdf" },
  { name: "Pose d’une attelle cervico-thoracique", pdf: "/Pose d’une attelle cervico-thoracique.pdf" },
  { name: "Pose d’un collier cervical", pdf: "/Pose d’un collier cervical.pdf" },
  { name: "Réalignement de membre", pdf: "/Réalignement de membre.pdf" },
  { name: "Retrait d’un casque de protection en secouriste isolé", pdf: "/Retrait d’un casque.pdf" },
  { name: "Retrait d’un casque de protection à 2", pdf: "/Retrait d’un casque.pdf" },
  { name: "Application de froid", pdf: "/Application de froid.pdf" },
  { name: "Emballage au moyen d’un pansement stérile", pdf: "/Emballage au moyen d’un pansement stérile.pdf" },
  { name: "Réaliser un pansement", pdf: "/Réaliser un pansement.pdf" },
  { name: "Maintien d'un pansement", pdf: "/Maintien d'un pansement.pdf" },
  { name: "Utilisation d’un lot membre sectionné", pdf: "/Utilisation d’un lot membre sectionné.pdf" },
  { name: "Aide à la marche", pdf: "/Aide à la marche.pdf" },
  { name: "Arrimage d’une victime sur un dispositif de transport", pdf: "/Arrimage d’une victime sur un dispositif de transport.pdf" },
  { name: "Brancardage à 4 sauveteurs : passage étroit", pdf: "/Brancardage à 4 sauveteurs.pdf" },
  { name: "Brancardage à 4 sauveteurs : en pente ou dans un escalier", pdf: "/Brancardage à 4 sauveteurs.pdf" },
  { name: "Brancardage à 3 sauveteurs : en terrain plat", pdf: "/Brancardage à 3 sauveteurs.pdf" },
  { name: "Brancardage à 3 sauveteurs : franchissement d’obstacle", pdf: "/Brancardage à 3 sauveteurs.pdf" },
  { name: "Brancardage à 3 sauveteurs : passage étroit", pdf: "/Brancardage à 3 sauveteurs.pdf" },
  { name: "Brancardage à 3 sauveteurs : en pente ou dans un escalier", pdf: "/Brancardage à 3 sauveteurs.pdf" },
  { name: "Déplacement par une chaise à « mains »", pdf: "/Déplacement par une chaise à « mains ».pdf" },
  { name: "Déplacement d'une victime non-valide", pdf: "/Déplacement d'une victime non-valide.pdf" },
  { name: "Installation d’une victime dans un VSAV", pdf: "/Installation d’une victime dans un VSAV.pdf" },
  { name: "Préparation d'un dispositif de portage", pdf: "/Préparation d'un dispositif de portage.pdf" },
  { name: "Relevage au moyen d’un brancard cuillère", pdf: "/Relevage au moyen d’un brancard cuillère.pdf" },
  { name: "Pont amélioré", pdf: "/Pont à 4 sauveteurs.pdf" },
  { name: "Pont néerlandais à 4 sauveteurs", pdf: "/Pont à 4 sauveteurs.pdf" },
  { name: "Pont simple", pdf: "/Pont à 3 sauveteurs.pdf" },
  { name: "Pont néerlandais à 3 sauveteurs", pdf: "/Pont à 3 sauveteurs.pdf" },
  { name: "Relevage d’une victime plat dos, cuisses fléchies", pdf: "/Relevage d’une victime particuliere.pdf" },
  { name: "Relevage d’une victime en PLS", pdf: "/Relevage d’une victime particuliere.pdf" },
  { name: "Relevage d’une victime assise sur une chaise de transport", pdf: "/Relevage d’une victime particuliere.pdf" },
  { name: "Relevage d’une victime en position demi-assise", pdf: "/Relevage d’une victime particuliere.pdf" },
  { name: "Transfert d’une victime à l’aide d’une alèse portoir", pdf: "/Transfert d’une victime à l’aide d’une alèse portoir.pdf" },
  { name: "Repérage nombreuses victimes", pdf: "/Repérage nombreuses victimes.pdf" },
  { name: "Extraction latérale d'une victime en position assise", pdf: "/Extraction latérale d'une victime en position assise.pdf" },
  { name: "Extraction latérale d'une victime en position allongée", pdf: "/Extraction latérale d'une victime en position allongée.pdf" },
  { name: "Extraction axiale d'une victime", pdf: "/Extraction axiale d'une victime.pdf" },
  { name: "Extraction oblique d'une victime", pdf: "/Extraction oblique d'une victime.pdf" },
  { name: "Extraction d'une victime affalée sur le capot", pdf: "/Extraction d'une victime affalée sur le capot.pdf" },
  { name: "Extraction d’une victime dans un véhicule immobilisé sur le toit", pdf: "/Extraction d’une victime dans un véhicule immobilisé sur le toit.pdf" },
  { name: "Extraction d’une victime dans un véhicule immobilisé sur le côté", pdf: "/Extraction d’une victime dans un véhicule immobilisé sur le côté.pdf" },
  { name: "Extraction d’une victime ceinturée dans un véhicule sur le toit", pdf: "/Extraction d’une victime ceinturée dans un véhicule sur le toit.pdf" },
  { name: "Extraction d’une victime dans un utilitaire ou sortie verticale", pdf: "/Extraction d’une victime dans un utilitaire ou sortie verticale.pdf" },
  { name: "Balisage en virage", pdf: "/Balisage en virage.pdf" },
  { name: "Balisage sur rond point", pdf: "/Balisage sur rond point.pdf" },
  { name: "Balisage sur voies bidirectionnelles", pdf: "/Balisage sur voies bidirectionnelles.pdf" },
  { name: "Balisage sur voies unidirectionnelles", pdf: "/Balisage sur voies unidirectionnelles.pdf" },
  { name: "Utilisation des balises lumineuses", pdf: "/Utilisation des balises lumineuses.pdf" },
  { name: "Utilisation des sangles rhinoevac", pdf: "/Utilisation des sangles rhinoevac.pdf" },
  { name: "Utilisation de l'explosimètre Altair 4X", pdf: "/Utilisation de l'explosimètre Altair 4X.pdf" },
  { name: "Utilisation de la pompe de l'explosimètre Altair 4X", pdf: "/Utilisation de la pompe de l'explosimètre Altair 4X.pdf" },
  { name: "Rideau stoppeur de fumée", pdf: "/Rideau stoppeur de fumée.pdf" },
  { name: "Utilisation des lances", pdf: "/Utilisation des lances.pdf" },
  { name: "Utilisation du halligan-tool", pdf: "/Utilisation du halligan-tool.pdf" },
  { name: "Echelle 1 plan téléscopique", pdf: "/Echelle 1 plan téléscopique.pdf" },
  { name: "Tuyaux avec réserve en spirale", pdf: "/Tuyaux avec réserve en spirale.pdf" },
  { name: "Detecteur CO", pdf: "/Detecteur CO.pdf" },
  { name: "Anti-vol VSAV", pdf: "/Anti-vol VSAV.pdf" },
  { name: "Couteau à vêtement", pdf: "/Couteau à vêtement.pdf" },
  { name: "Coussin de tête", pdf: "/Coussin de tête.pdf" },
  { name: "Pédimat", pdf: "/Pédimat.pdf" },
  { name: "Corde flottante", pdf: "/Corde flottante.pdf" },
  { name: "Ceinturon d'intervention", pdf: "/Ceinturon d'intervention.pdf" },
  { name: "Communication opérationnel-utilisation des radios", pdf: "/Communication opérationnel-utilisation des radios.pdf" },
  { name: "Secours éléctrique du CIS", pdf: "/Secours éléctrique du CIS.pdf" },
  /*
{ name: "Transfert d’une victime méthode de la cuillère", pdf: "/Transfert d’une victime méthode de la cuillère.pdf" },
{ name: "Déshabiller un sauveteur inconscient tenue de feu", pdf: "/Déshabiller un sauveteur inconscient tenue de feu.pdf" },
{ name: "Optimisation du dispositif de ventilation", pdf: "/Optimisation du dispositif de ventilation.pdf" },
{ name: "Ventilation par entraînement d'air aux lances", pdf: "/Ventilation par entraînement d'air aux lances.pdf" },
{ name: "Rideau stoppeur fumée", pdf: "/Rideau stoppeur fumée.pdf" },
{ name: "Utilisation échelle à coulisse", pdf: "/Utilisation échelle à coulisse.pdf" },
{ name: "Détecteur multigaz", pdf: "/Détecteur multigaz.pdf" },
{ name: "Mise en place de l'éclairage", pdf: "/Mise en place de l'éclairage.pdf" },
{ name: "Pompe prélèvement", pdf: "/Pompe prélèvement.pdf" },
{ name: "LSPCC-Progression horizontale", pdf: "/LSPCC-Progression horizontale.pdf" },
{ name: "Ouverture de porte Halligan+masse", pdf: "/Ouverture de porte Halligan+masse.pdf" },
{ name: "Envoyer un message de détresse", pdf: "/Envoyer un message de détresse.pdf" },
{ name: "Utilisation TGR", pdf: "/Utilisation TGR.pdf" },
{ name: "CCRM-Utilisation du chariot de balisage", pdf: "/CCRM-Utilisation du chariot de balisage.pdf" },
{ name: "Utilisation d'un extincteur", pdf: "/Utilisation d'un extincteur.pdf" },
{ name: "Accident d’exposition à un risque viral", pdf: "/Accident d’exposition à un risque viral.pdf" },
{ name: "Bilan d’urgence : XABCDE", pdf: "/Bilan d’urgence : XABCDE.pdf" },
{ name: "Évaluer la motricité et la sensibilité", pdf: "/Évaluer la motricité et la sensibilité.pdf" },
{ name: "Examiner les pupilles", pdf: "/Examiner les pupilles.pdf" },
{ name: "Rechercher et apprécier le pouls carotidien", pdf: "/Rechercher et apprécier le pouls carotidien.pdf" },
{ name: "Rechercher et apprécier le pouls radial", pdf: "/Rechercher et apprécier le pouls radial.pdf" },
{ name: "Rechercher et apprécier le pouls huméral", pdf: "/Rechercher et apprécier le pouls huméral.pdf" },
{ name: "Rechercher et apprécier le pouls fémoral", pdf: "/Rechercher et apprécier le pouls fémoral.pdf" },
{ name: "Mesurer le temps de recoloration cutanée", pdf: "/Mesurer le temps de recoloration cutanée.pdf" },
{ name: "Examen de la peau et des muqueuses", pdf: "/Examen de la peau et des muqueuses.pdf" },
{ name: "Bilan complémentaire malade malaise", pdf: "/Bilan complémentaire malade malaise.pdf" },
{ name: "Surveillance de la victime", pdf: "/Surveillance de la victime.pdf" },
{ name: "Arroser une brûlure", pdf: "/Arroser une brûlure.pdf" },
{ name: "Compression d’un saignement de nez", pdf: "/Compression d’un saignement de nez.pdf" },
{ name: "Installation d’une victime dans un VSAV", pdf: "/Installation d’une victime dans un VSAV.pdf" },
{ name: "Utilisation des emballages à élimination de déchets", pdf: "/Utilisation des emballages à élimination de déchets.pdf" },
{ name: "Utilisation d'une tronçonneuse", pdf: "/Utilisation d'une tronçonneuse.pdf" },
{ name: "Mise en place d'un groupe électrogène", pdf: "/Mise en place d'un groupe électrogène.pdf" },
{ name: "Aspiration avec MPE", pdf: "/Aspiration avec MPE.pdf" },
{ name: "Aspiration avec pompe électrique", pdf: "/Aspiration avec pompe électrique.pdf" },
{ name: "Capture de serpent", pdf: "/Capture de serpent.pdf" },
{ name: "Capture d'animaux au moyen du lasso", pdf: "/Capture d'animaux au moyen du lasso.pdf" },
{ name: "Assèchement avec aspirateur", pdf: "/Assèchement avec aspirateur.pdf" },*/
  // Ajoutez plus de techniques selon vos besoins
          ];
  
          let technique = genererTechnique()
  
          function genererTechnique() {
              const nombre = Math.floor(Math.random() * techniques.length);
              return techniques[nombre];
          }
  
          genererTechnique();
  </script>
  
  <main>
    <h1>Générateur de Technique</h1>
    <div class="container">
      <div class="text">
        <p>Cliquez sur le bouton pour générer une technique</p>
      </div>
      <button on:click={() => { technique = genererTechnique(); }}>Générer</button>
      <div class="result">
        <p>{technique.name}</p>
        <a href="{technique.pdf}" target="_blank">Voir le PDF</a>
      </div>
    </div>
    <div class="mail">
      <a href="mailto:plbd@laposte.net">Suggérer une amélioration ?</a>
    </div>
  </main>