<script lang="ts">
  
const techniques = [

"ETB1-Ldt",
"ETB2-Prise d'eau",
"ETB3-Lance",
"ETB4-Alimentation",
"ETB5-Etablissement particuliers",
"ETB6-Prolongement/remplacement",
"TDE1-Refroidissement des fumées",
"TDE2-Extinction directe",
"TDE3-Extinction indirecte",
"TDE4-Extinction combinée/massive",
"TDE5-Situation pre-backdraft",
"TDE6-Repli sous protection hydraulique",
"TDE7-Feu soumis aux effets du vent et effet chalumeau",
"TDE8-Attaque d'atténuation",
"Appareils de protection respiratoire",
"Engagement a vue",
"Engagement au moyen d'une ligne de vie",
"Engagement sur ligne de vie méthode latérale",
"Engagement sur ligne de vie méthode circulaire",
"Règle de marquage",
"Passage dans des fils ou des câbles",
"Itinéraires et évacuation générale",
"Franchissement passage étroit",
"Auto-sauvetage",
"Attendre les secours",
"Packaging-Abordage du sauveteur",
"Traction au sol avec matériel",
"Traction au sol sans matériel",
"Mission binôme sécurité",
"Habillage",
"Déshabiller un sauveteur inconscient tenue de feu",
"Contrôle croisé",
"Mission contrôleur",
"Optimisation du dispositif de ventilation",
"Ventilation par entraînement d'air aux lances",
"LSPCC-Sauvetage au moyen du harnais",
"Rideau stoppeur fumée",
"Utilisation échelle à coulisse",
"Utilisation de l'échelle à crochet",
"Détecteur multigaz",
"Mise en place de l'éclairage",
"Pompe prélèvement",
"LSPCC-Excavation",
"LSPCC-Sauvetage extérieur",
"LSPCC-Progression horizontale",
"Ouverture de porte Halligan+masse",
"Envoyer un message de détresse",
"Utilisation TGR",
"Décontamination aux fumées d'incendie",
"Technique de respiration (gestion air)",
"Gérer une fuite",
"CCRM-Utilisation du chariot de balisage",
"Utilisation d'un extincteur",
"Lavage des mains à l’eau et au savon",
"Friction des mains avec une solution hydroalcoolique",
"Équipement de protection risques infectieux",
"Retrait des gants à usage unique",
"Accident d’exposition à un risque viral",
"Traction par les chevilles",
"Traction par les poignets",
"Traction par les vêtements",
"Traction sous les aisselles",
"Sortie d’un véhicule",
"Dégagement d’un enfant ou d’un nourrisson",
"Traction sur le sol par équipier relais",
"Bilan circonstanciel",
"Bilan d’urgence : XABCDE",
"Apprécier la conscience, l’orientation et la PCI",
"Évaluer la motricité et la sensibilité",
"Examiner les pupilles",
"LVA victime assise",
"LVA victime non traumatisée",
"LVA victime traumatisée",
"Apprécier la respiration",
"Mesure de la saturation en oxygène",
"Rechercher et apprécier le pouls carotidien",
"Rechercher et apprécier le pouls radial",
"Rechercher et apprécier le pouls huméral",
"Rechercher et apprécier le pouls fémoral",
"Mesurer le temps de recoloration cutanée",
"Mesurer la pression artérielle (auto-tensiomètre)",
"Examen de la peau et des muqueuses",
"Bilan complémentaire malade malaise",
"Mesurer la température de la victime",
"Position d’attente à plat dos",
"Position d’attente assise ou demi-assise",
"Position d’attente sur le côté",
"Position d’attente cuisses fléchies, jambes repliées",
"Bilan complémentaire traumatisé",
"Surveillance de la victime",
"Claques dans le dos (adulte et enfant)",
"Compressions abdominales (adulte et enfant)",
"Compressions thoraciques (femme enceinte et obèse)",
"Claques dans le dos (nourrisson)",
"Compressions thoraciques (nourrisson)",
"Utilisation d’une bouteille d’oxygène",
"Inhalation d’oxygène (masque haute concentration)",
"Aspiration de mucosités",
"Maintien de la tête à 2 mains victime plat dos",
"Retrait d’un casque de protection à 1",
"Retrait d’un casque de protection à 2",
"Pose d’un collier cervical",
"PLS à 1 secouriste",
"PLS à 2 secouristes",
"Retournement en urgence d’une victime à 2",
"Retournement en urgence d’une victime à 1",
"Compressions thoraciques (adultes)",
"Compressions thoraciques (enfant)",
"Ventilation artificielle orale (adulte, enfant)",
"Compressions thoraciques (nourrisson, nouveau-né)",
"Ventilation artificielle orale (nourrisson, nouveau-né)",
"Arroser une brûlure",
"Emballage au moyen d’un pansement stérile",
"Ventilation artificielle avec insufflateur (1 secouriste)",
"Ventilation artificielle avec insufflateur (2 secouristes)",
"Mise en place d’une canule oropharyngée",
"Utilisation du DAE",
"Compression manuelle directe",
"Pose d’un garrot",
"Pose d’un pansement compressif (israélien)",
"Utilisation d’un lot membre sectionné",
"Réaliser un pansement",
"Écharpe simple",
"Contre-écharpe",
"Écharpe oblique",
"Application de froid",
"Compression d’un saignement de nez",
"Aide à la prise de médicaments",
"Maintien de la tête à 2 mains victime debout ou assise",
"Pose d’une attelle cervico-thoracique",
"Sortie longitudinale (VL sur ses roues)",
"Sortie latérale (VL sur ses roues)",
"Sortie oblique (VL sur ses roues)",
"Sortie de victime VL sur le flanc",
"Victime ceinturée suspendue",
"Sortie d’une victime non ceinturée sur le dos VL sur le toit",
"Arrimage d’une victime sur un dispositif de transport",
"Installation d’une victime dans un VSAV",
"Brancardage à 4 sauveteurs passage étroit",
"Brancardage à 4 sauveteurs en pente ou dans un escalier",
"Brancardage à 3 sauveteurs en terrain plat",
"Brancardage à 3 sauveteurs franchissement d’obstacle",
"Brancardage à 3 sauveteurs passage étroit",
"Brancardage à 3 sauveteurs en pente ou dans un escalier",
"Déplacement par une chaise à « mains »",
"Saisie par les extrémités",
"Aide à la marche à 1 secouriste",
"Aide à la marche à 2 secouristes",
"Repérage nombreuses victimes",
"Mesurer la glycémie capillaire",
"Nettoyage et désinfection d’un véhicule ou d’un local",
"Nettoyage et désinfection du matériel",
"Utilisation des emballages à élimination de déchets",
"Transfert d’une victime méthode de la cuillère",
"Transfert d’une victime à l’aide d’une alèse portoir",
"Préparation d’un dispositif de transport",
"Pont simple",
"Pont néerlandais à 3 sauveteurs",
"Pont amélioré",
"Pont néerlandais à 4 sauveteurs",
"Relevage au moyen d’un brancard cuillère",
"Relevage d’une victime plat dos, cuisses fléchies",
"Relevage d’une victime en PLS",
"Relevage d’une victime assise sur une chaise de transport",
"Relevage d’une victime en position demi-assise",
"Immobilisation au moyen du MID",
"Immobilisation victime plat dos sur plan dur",
"Immobilisation victime allongée sur le ventre sur plan dur",
"Immobilisation victime debout sur plan dur",
"Réalignement de membre",
"Pose d’attelle à dépression membre supérieur et membre inférieur",
"Utilisation d'une tronçonneuse",
"Mise en place d'un groupe électrogène",
"Aspiration avec MPE",
"Aspiration avec pompe électrique",
"Capture de serpent",
"Capture d'animaux au moyen du lasso",
"Assèchement avec aspirateur",
// Ajoutez plus de techniques selon vos besoins
        ];

        let technique = genererTechnique()

        function genererTechnique() {
            const nombre = Math.floor(Math.random() * techniques.length);
            return techniques[nombre];
        }

        genererTechnique();
</script>

<main>
  <h1>Générateur de Technique</h1>
  <div class="container">
      <p>Cliquez sur le bouton pour générer une technique</p>
      <button on:click={() => {technique = genererTechnique()}}>Générer</button>
      <div class="result">
        {technique}
      </div>
  </div>
</main>
