<script lang="ts">
  
const techniques = [

"ETB1-LDT",
"ETB2-PRISE D'EAU",
"ETB3-LANCE",
"ETB4-ALIMENTATION",
"ETB5-ETABLISSEMENT PARTICULIERS",
"ETB6-PROLONGEMENT/REMPLACEMENT",
"TDE 1 Refroidissement des fumées",
"TDE-2 EXTINCTION DIRECTE",
"TDE3-EXTINCTION INDIRECTE",
"TDE4-EXTINCTION COMBINEE/MASSIVE",
"TDE5-SITUATION PRE-BACKDRAFT",
"TDE6-REPLI SOUS PROTECTION HYDRAULIQUE",
"TDE7-FEU SOUMIS AUX EFFETS DU VENT ET EFFET CHALUMEAU",
"TDE8-ATTAQUE D'ATTENUATION",
"APPAREILS DE PROTECTION RESPIRATOIRE",
"ENGAGEMENT A VUE",
"ENGAGEMENT AU MOYEN D'UNE LIGNE DE VIE",
"ENGAGEMENT SUR LIGNE DE VIE METHODE LATERALE",
"ENGAGEMENT SUR LIGNE DE VIE METHODE CIRCULAIRE",
"REGLE DE MARQUAGE",
"PASSAGE DANS DES FILS OU DES CABLES",
"ITINERAIRES ET EVACUATION GENERALE",
"FRANCHISSEMENT PASSAGE ETROIT",
"AUTO-SAUVETAGE",
"ATTENDRE LES SECOURS",
"packaging-ABORDAGE DU SAUVETEUR",
"traction au sol avec matériel",
"traction au sol sans matériel .",
"MISSION BINOME SECURITE",
"HABILLAGE",
"DESHABILLER UN SAUVETEUR INCONSCIENT TENUE DE FEU",
"CONTROLE CROISE",
"MISSION CONTROLEUR",
"OPTIMISATION DU DISPOSITIF DE VENTILATION",
"VENTILATION PAR ENTRAINEMENT D'AIR AUX LANCES",
"LSPCC-SAUVETAGE AU MOYEN DU HARNAIS",
"Rideau stoppeur fumée",
"Utilisation Echelle à coulisse",
"utilisation de l'échelle à crochet",
"Détécteur multiGaz",
"MISE EN PLACE DE L'ECLAIRAGE",
"Pompe prélévement",
"LSPCC-Excavation",
"LSPCC-Sauvetage extérieur",
"LSPCC-Progression horizontale",
"Ouverture de porte Halligan+Masse",
"envoyer un message de detresse",
"utilisation TGR",
"DECONTAMINATION AUX FUMEES D'INCENDIE",
"technique de respiration (gestion air)",
"gerer une fuite",
"CCRM-UTILISATION DU CHARIOT DE BALISAGE",
"UTILISATION D'UN EXTINCTEUR",
"Lavage des mains à l’eau et au savon",
"Friction des mains avec une solution hydro alcoolique",
"Equipement de protection risques infectieux",
"Retrait des gants à usage unique",
"Accident d’exposition à un risque viral",
"Traction par les chevilles",
"Traction par les poignets",
"Traction par les vêtements",
"Traction sous les aisselles",
"Sortie d’un véhicule",
"Dégagement d’un enfant ou d’un nourrisson",
"Traction sur le sol par équipier relais",
"Bilan circonstanciel",
"Bilan d’urgence : XABCDE",
"Apprécier la conscience, l’orientation et la PCI",
"Evaluer la motricité et la sensibilité",
"Examiner les pupilles",
"LVA victime assise",
"LVA victime non traumatisée",
"LVA victime traumatisée",
"Apprécier la respiration",
"Mesure de la saturation en oxygène",
"Rechercher et apprécier le pouls carotidien",
"Rechercher et apprécier le pouls radial",
"Rechercher et apprécier le pouls huméral",
"Rechercher et apprécier le pouls fémoral",
"Mesurer le temps de recoloration cutanée",
"Mesurer la pression artérielle (auto tensiomètre)",
"Examen de la peau et des muqueuses",
"Bilan complémentaire malade malaise",
"Mesurer la température de la victime",
"Position d’attente à plat dos",
"Position d’attente assise ou demi-assise",
"Position d’attente sur le côté",
"Position d’attente cuisses fléchies, jambes repliées",
"Bilan complémentaire traumatisé",
"Surveillance de la victime",
"Claques dans le dos (adulte et enfant)",
"Compressions abdominales (adulte et enfant)",
"Compressions thoraciques (femme enceinte et obèse)",
"Claques dans le dos (nourrisson)",
"Compressions thoraciques (nourrisson)",
"Utilisation d’une bouteille d’oxygène",
"Inhalation d’oxygène (masque haute concentration)",
"Aspiration de mucosités",
"Maintien de la tête à 2 mains victime plat dos",
"Retrait d’un casque de protection à 1",
"Retrait d’un casque de protection à 2",
"Pose d’un collier cervical",
"PLS à 1 secouriste",
"PLS à 2 secouristes",
"Retournement en urgence d’une victime à 2",
"Retournement en urgence d’une victime à 1",
"Compressions thoraciques (adultes)",
"Compressions thoraciques (enfant)",
"Ventilation artificielle orale (adulte, enfant)",
"Compressions thoraciques (nourrisson, nouveau-né)",
"Ventilation artificielle orale (nourrisson, nouveau-né)",
"Arroser une brûlure",
"Emballage au moyen d’un pansement stérile",
"Ventilation artificielle avec insufflateur (1 secouriste)",
"Ventilation artificielle avec insufflateur (2 secouristes)",
"Mise en place d’une canule oro-pharyngée",
"Utilisation du DAE",
"Compression manuelle directe",
"Pose d’un garrot",
"Pose d’un pansement compressif (israelien)",
"Utilisation d’un lot membre sectionné",
"Réaliser un pansement",
"Echarpe simple",
"Contre écharpe",
"Echarpe oblique",
"Application de froid",
"Compression d’un saignement de nez",
"Aide à la prise de médicaments",
"Maintien de la tête à 2 mains victime debout ou assise",
"Pose d’une attelle cervico-thoracique",
"Sortie longitudinale (VL sur ses roues)",
"Sortie latérale (VL sur ses roues)",
"Sortie Oblique (VL sur ses roues)",
"Sortie de victime VL sur le Flanc",
"Victime ceinturée suspendue",
"Sortie d’une victime non ceinturée sur le dos VL sur le toit",
"Arrimage d’une victime sur un dispositif de transport",
"Installation d’une victime dans un VSAV",
"Brancardage à 4 sauveteurs passage étroit",
"Brancardage à 4 sauveteurs en pente ou dans un escalier",
"Brancardage à 3 sauveteurs en terrain plat",
"Brancardage à 3 sauveteurs franchissement d’obstacle",
"Brancardage à 3 sauveteurs passage étroit",
"Brancardage à 3 sauveteurs en pente ou dans un escalier",
"Déplacement par une chaise à « mains »",
"Saisie par les extrémités",
"Aide à la marche à 1 secouriste",
"Aide à la marche à 2 secouristes",
"Repérage nombreuses victimes",
"Mesurer la glycémie capillaire",
"Nettoyage et désinfection d’un véhicule ou d’un local",
"Nettoyage et désinfection du matériel",
"Utilisation des emballages à élimination de déchets",
"Transfert d’une victime méthode de la cuillère",
"Transfert d’une victime à l’aide d’une alèse portoir",
"Préparation d’un dispositif de transport",
"Pont simple",
"Pont néerlandais à 3 sauveteurs",
"Pont amélioré",
"Pont néerlandais à 4 sauveteurs",
"Relevage au moyen d’un brancard cuillère",
"Relevage d’une victime plat dos, cuisses fléchies",
"Relevage d’une victime en PLS",
"Relevage d’une victime assise sur une chaise de transport",
"Relevage d’une victime en position demi-assise",
"Immobilisation au moyen du MID",
"Immobilisation victime plat dos sur plan dur",
"Immobilisation victime allongée sur le ventre sur plan dur",
"Immobilisation victime debout sur plan dur",
"Réalignement de membre",
"Pose d’attelle à dépression membre supérieur et membre inférieur",
"UTILISATION D'UNE TRONCONNEUSE",
"MISE EN PLACE D'UN GROUPE ELECTROGENE",
"ASPIRATION AVEC MPE",
"ASPIRATION AVEC POMPE ELECTRIQUE",
"CAPTURE DE SERPENT",
"CAPTURE D'ANIMAUX AU MOYEN DU LASSO",
"ASSECHEMENT AVEC ASPIRATEUR",
// Ajoutez plus de techniques selon vos besoins
        ];

        let technique = genererTechnique()

        function genererTechnique() {
            const nombre = Math.floor(Math.random() * techniques.length);
            return techniques[nombre];
        }

        genererTechnique();
</script>

<main>
  <h1>Générateur de Technique</h1>
  <div class="container">
      <p>Cliquez sur le bouton pour générer une technique</p>
      <button on:click={() => {technique = genererTechnique()}}>Générer</button>
      <div class="result">
        {technique}
      </div>
  </div>
</main>
